package encoding

import (
	"crypto/aes"
	"crypto/cipher"
	cryptorand "crypto/rand"
	"errors"
	"fmt"
)

var aesRandRead = cryptorand.Read

var aesGCMCiphertextPrefix = []byte("PAG1")

// EncryptAES encrypts the given plaintext using AES-GCM authenticated encryption.
// The key must be either 16, 24, or 32 bytes long.
func EncryptAES(plain []byte, key []byte) ([]byte, error) {
	gcm, err := newAESGCM(key)
	if err != nil {
		return nil, err
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := aesRandRead(nonce); err != nil {
		return nil, fmt.Errorf("aes-gcm nonce generation failed: %w", err)
	}

	out := make([]byte, 0, len(aesGCMCiphertextPrefix)+len(nonce)+len(plain)+gcm.Overhead())
	out = append(out, aesGCMCiphertextPrefix...)
	out = append(out, nonce...)
	out = gcm.Seal(out, nonce, plain, nil)
	return out, nil
}

// DecryptAES decrypts ciphertext generated by EncryptAES.
// The key must be either 16, 24, or 32 bytes long.
func DecryptAES(ciphertext []byte, key []byte) ([]byte, error) {
	gcm, err := newAESGCM(key)
	if err != nil {
		return nil, err
	}

	prefixLen := len(aesGCMCiphertextPrefix)
	minLen := prefixLen + gcm.NonceSize() + gcm.Overhead()
	if len(ciphertext) < minLen {
		return nil, errors.New("ciphertext is too short")
	}
	if string(ciphertext[:prefixLen]) != string(aesGCMCiphertextPrefix) {
		return nil, errors.New("unsupported ciphertext format")
	}

	nonceStart := prefixLen
	nonceEnd := nonceStart + gcm.NonceSize()
	nonce := ciphertext[nonceStart:nonceEnd]
	encrypted := ciphertext[nonceEnd:]

	plain, err := gcm.Open(nil, nonce, encrypted, nil)
	if err != nil {
		return nil, fmt.Errorf("aes-gcm authentication failed: %w", err)
	}
	return plain, nil
}

func newAESGCM(key []byte) (cipher.AEAD, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	gcm, _ := cipher.NewGCM(block)
	return gcm, nil
}
